export const GET_DOCTOR_TYPE = "GET_DOCTOR_TYPE";
export const CREATE_DOCTOR_TYPE = "CREATE_DOCTOR_TYPE";
export const DELETE_DOCTOR_TYPE = "DELETE_DOCTOR_TYPE";
export const UPDATE_DOCTOR_TYPE = "UPDATE_DOCTOR_TYPE";