export const CREATE_DOCTOR_SLOT = "CREATE_DOCTOR_SLOT";
export const GET_DOCTOR_APPOINMENTS = "GET_DOCTOR_APPOINMENTS";
export const CREATE_DOCTOR_SLOT_ERROR = "CREATE_DOCTOR_SLOT_ERROR";
export const UPDATE_DOCTOR_APPOINMENTS = "UPDATE_DOCTOR_APPOINMENTS";